name: ci

on: [push, workflow_dispatch]

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: snazzybucket/idris2
    steps:
      - uses: actions/checkout@v2
      - name: typechecking
        run: make check
  test:
    needs: check
    runs-on: ubuntu-latest
    container:
      image: snazzybucket/idris2
    steps:
      - name: Checkout replica
        uses: actions/checkout@v2
        with:
          repository: berewt/replica
          path: .replica
      - name: Install replica
        run: |
          pushd .replica
          make install
          popd
      - uses: actions/checkout@v2
      - name: build, install, and test
        run: make test

