name: ci

on: [push, workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: snazzybucket/idris2
    steps:
      - uses: actions/checkout@v2
      - name: typechecking
        run: make check
      - uses: actions/upload-artifact@v2
        with:
          name: india-pkg
          path: build/ttc

  replica:
    runs-on: ubuntu-latest
    container:
      image: snazzybucket/idris2
    steps:
      - name: Checkout replica
        uses: actions/checkout@v2
        with:
          repository: berewt/replica
      - uses: actions/upload-artifact@v2
        with:
          name: replica-exe
          path: build/exec

  test:
    needs: [build, replica]
    runs-on: ubuntu-latest
    container:
      image: snazzybucket/idris2
    env:
      IDRIS2_PACKAGE_PATH: $GITHUB_WORKSPACE/depends
    steps:
      - uses: actions/checkout@v2
      - name: reinstall artifact
      - uses: actions/download-artifact@v2
         with:
           name: india-pkg
           path: depends/india
      - uses: actions/download-artifact@v2
         with:
           name: replica-exe
      - name: test
        run: replica-exe/replica tests
